apiVersion: v1
kind: Secret
metadata:
  name: municipal-secret
  namespace: municipal

type: Opaque

stringData:
  SECRET_KEY: "supersecretkey"

  DATABASE_URL: "postgresql://postgres:alok6969@municipaldb.c7aegamwgk05.ap-south-1.rds.amazonaws.com:5432/postgres"

  BUCKET_NAME: "alokkkkk1234"

  SNS_TOPIC_ARN: "arn:aws:sns:ap-south-1:519120506792:complaint-notifications"

  AWS_REGION: "ap-south-1"